### ISSUE TITLE
PIC dataset

### ISSUE THREAD

**Issue by SherlockHolmes221** [DirtyHarryLYL/HAKE#4]
Where I can download **pic dataset**?  this link? http://picdataset.com/challenge/task/download/ and 2019 or 2018 version? Thanks!

**Comment by DirtyHarryLYL** [comment]
In terms of the time, it should be PIC 2018. But to be careful, please download the data to compare HAKE labels and the corresponding PIC images.

**Comment by SherlockHolmes221** [comment]
Thx

**Comment by linzhiqiu** [comment]
The link is expired again -- do you have a new link or could you provide a google drive zip file?

**Comment by DirtyHarryLYL** [comment]
Maybe try to contact the PIC team for the data?

**Comment by linzhiqiu** [comment]
I couldn't seem to find the PIC paper and their authors on the web. Do you know the paper title or author names?

**Comment by DirtyHarryLYL** [comment]
https://www.jiqizhixin.com/articles/2021-04-11-4
