### ISSUE TITLE
PIC dataset cannot be downloaded

### ISSUE THREAD

**Issue by linzhiqiu** [DirtyHarryLYL/HAKE#6]
The link is expired

**Comment by kkjh0723** [comment]
@linzhiqiu Did you download PIC dataset? Could you please share the dataset?

**Comment by linzhiqiu** [comment]
I downloaded it in my google drive and will share the link later in my new repo: https://github.com/linzhiqiu/visual_gpt_score/

**Comment by kkjh0723** [comment]
@linzhiqiu Thanks for the information. I set watch on your repo. Do you have any schedule to share the link? It would be even better if I can get an early access link.

**Comment by linzhiqiu** [comment]
I plan to release it by next weekend, but feel free to shoot me an email for a private link: zhiqiul@andrew.cmu.edu
