### ISSUE TITLE
hico_20160224_det is no longer available

### ISSUE THREAD

**Issue by linzhiqiu** [DirtyHarryLYL/HAKE#7]
This URL is no longer available: http://napoli18.eecs.umich.edu/public_html/data/hico_20160224_det.tar.gz

**Comment by DirtyHarryLYL** [comment]
Maybe try to contact the HICO team?

**Comment by linzhiqiu** [comment]
I addressed this issue via this new link: 
```
import gdown
subprocess.call(["gdown", "--id", "1QZcJmGVlF9f4h-XLWe9Gkmnmj2z1gSnk"])
```
