### ISSUE TITLE
Which split of PIC dataset should I use

### ISSUE THREAD

**Issue by jonghakim35** [DirtyHarryLYL/HAKE#8]
Hi, thanks for sharing your work.

I have a question while preparing the dataset following the instructions in the [link](https://github.com/DirtyHarryLYL/HAKE/tree/master/Images#download-images-for-hake).

I've downloaded PIC dataset, but wondering which split should I get images from. 

In detail, there seems train/val/test splits exist in the PIC dataset, and should I put all images from train/val/test under the images/pic directory? Or should I use only the specific set of images?

**Comment by DirtyHarryLYL** [comment]
The detailed list of the used PIC images are in https://github.com/DirtyHarryLYL/HAKE/blob/master/Images/imagelist/pic.txt

**Comment by jonghakim35** [comment]
Thanks for the clarification.
Just for double-checking: so do I have to remove every images that are not listed in [list files](https://github.com/DirtyHarryLYL/HAKE/tree/master/Images/imagelist) for other datasets (HAKE, openimages, vcoco...) as well?

**Comment by DirtyHarryLYL** [comment]
Keeping or removing is OK, except that you may use the uncollected images for some other purposes.
