### ISSUE TITLE
the download link of pic dataset seems crashed

### ISSUE THREAD

**Issue by yestinl** [DirtyHarryLYL/HAKE#9]
The download link of pic dataset seems crashed, could you upload it to google drive and give me the link? Thanks

**Comment by yestinl** [comment]
Also, the link of hico_det(http://napoli18.eecs.umich.edu/public_html/data/hico_20160224_det.tar.gz) is unavailable.

**Comment by DirtyHarryLYL** [comment]
1. PIC: https://github.com/DirtyHarryLYL/HAKE/issues/6

3. HICO-DET: https://github.com/DirtyHarryLYL/HAKE/issues/7#issuecomment-1516770730

**Comment by yestinl** [comment]
Thank you very much!
